{% set version = "0.18.0" %}

package:
  name: jedi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jedi/jedi-{{ version }}.tar.gz
  sha256: 92550a404bad8afed881a137ec9a461fed49eca661414be45059329614ed0707

build:
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - parso >=0.8.0,<0.9.0

test:
  requires:
    - pip
  imports:
    - jedi
    - jedi.api
    - jedi.common
    - jedi.inference
    - jedi.inference.compiled
    - jedi.inference.compiled.subprocess
    - jedi.inference.gradual
    - jedi.inference.value
    - jedi.plugins
  commands:
    - python -m pip check

about:
  home: https://github.com/davidhalter/jedi/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An autocompletion tool for Python that can be used for text editors.
  description: |
    Jedi is a static analysis tool for Python that can be used in IDEs/editors.
    Its historic focus is autocompletion, but does static analysis for now as
    well. Jedi is fast and is very well tested. It understands Python on a
    deeper level than all other static analysis frameworks for Python.
  dev_url: https://github.com/davidhalter/jedi/
  doc_url: http://jedi.readthedocs.io/en/latest/
  doc_source_url: https://github.com/davidhalter/jedi/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - goanpeca
    - asmeurer
    - nehaljwani
    - ocefpaf
